
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;




/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
 

/**
 *
 * @author Zoha Saleem
 */

public class WeatherApplication extends javax.swing.JFrame {

    
    public WeatherApplication() {
        initComponents();
    }
    //String city1="Karachi";
String info[]={"KARACHI","LAHORE","ISLAMABAD","QUETTA","PESHAWAR","MURREE","LONDON","PARIS","NEW YORK","NEW DEHLI","MUMBAI","HYDERABAD","RAWALPINDI"};

    
    

    /**
     * 
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        textField = new javax.swing.JTextField();
        temperature = new javax.swing.JLabel();
        checkWeather = new javax.swing.JButton();
        myCity = new javax.swing.JLabel();
        humidity = new javax.swing.JLabel();
        weather = new javax.swing.JLabel();
        rain = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setLayout(null);

        textField.setBackground(new java.awt.Color(153, 51, 0));
        textField.setForeground(new java.awt.Color(204, 204, 204));
        textField.setText("  ENTER A CITY");
        textField.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        textField.setCaretColor(new java.awt.Color(0, 0, 0));
        textField.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                textFieldMouseClicked(evt);
            }
        });
        textField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldActionPerformed(evt);
            }
        });
        textField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                textFieldKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                textFieldKeyReleased(evt);
            }
        });
        jPanel1.add(textField);
        textField.setBounds(10, 430, 210, 40);

        temperature.setFont(new java.awt.Font("Calibri", 1, 36)); // NOI18N
        temperature.setForeground(new java.awt.Color(204, 204, 204));
        temperature.setText("°C");
        jPanel1.add(temperature);
        temperature.setBounds(300, 120, 130, 60);

        checkWeather.setBackground(new java.awt.Color(153, 51, 0));
        checkWeather.setFont(new java.awt.Font("Calibri", 1, 12)); // NOI18N
        checkWeather.setForeground(new java.awt.Color(204, 204, 204));
        checkWeather.setText("Check Weather");
        checkWeather.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        checkWeather.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkWeatherActionPerformed(evt);
            }
        });
        jPanel1.add(checkWeather);
        checkWeather.setBounds(310, 430, 120, 40);

        myCity.setFont(new java.awt.Font("Calibri", 1, 48)); // NOI18N
        myCity.setForeground(new java.awt.Color(204, 204, 204));
        myCity.setText("     CITY");
        jPanel1.add(myCity);
        myCity.setBounds(120, 40, 270, 80);

        humidity.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        humidity.setForeground(new java.awt.Color(204, 204, 204));
        humidity.setText("Humidity:");
        jPanel1.add(humidity);
        humidity.setBounds(20, 150, 120, 30);

        weather.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        weather.setForeground(new java.awt.Color(204, 204, 204));
        weather.setText("Weather:");
        jPanel1.add(weather);
        weather.setBounds(20, 180, 130, 30);

        rain.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        rain.setForeground(new java.awt.Color(204, 204, 204));
        rain.setText("Rain:");
        jPanel1.add(rain);
        rain.setBounds(20, 210, 130, 30);

        jButton1.setBackground(new java.awt.Color(153, 51, 0));
        jButton1.setForeground(new java.awt.Color(204, 204, 204));
        jButton1.setText("←");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(0, 480, 46, 20);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/weatherapp/images/image1.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 450, 500);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(450, 499));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void textFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldActionPerformed
        
    }//GEN-LAST:event_textFieldActionPerformed

    private void checkWeatherActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkWeatherActionPerformed
        weatherConditions();
    }//GEN-LAST:event_checkWeatherActionPerformed

    private void textFieldKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER)
        {
            weatherConditions();
        }
        
    }//GEN-LAST:event_textFieldKeyPressed

    private void textFieldKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_textFieldKeyReleased
       int position=textField.getCaretPosition();
       textField.setText(textField.getText().toUpperCase());
       textField.setCaretPosition(position);
    }//GEN-LAST:event_textFieldKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        this.setVisible(false);
        new Apps().setVisible(true);
    }//GEN-LAST:event_jButton1MouseClicked

    private void textFieldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_textFieldMouseClicked
        textField.setText("");
    }//GEN-LAST:event_textFieldMouseClicked

    public void weatherConditions()
    {
        String city=textField.getText();
        if(city.equals(info[0]))
        {
        myCity.setText("KARACHI");
        temperature.setText("20 °C");
        weather.setText("Partially Cloudy");
        humidity.setText("Humidity: 65 %");
        rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[1]))
        {
            myCity.setText("LAHORE");
            temperature.setText("13 °C");
            weather.setText("Clear");
            humidity.setText("Humidity: 80 %");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[2]))
        {
            myCity.setText("ISLAMABAD");
            temperature.setText("10 °C");
            weather.setText("Overcast");
            humidity.setText("Humidity: 93%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[3]))
        {
            myCity.setText("QUETTA");
            temperature.setText("7 °C");
            weather.setText("Cloudy");
            humidity.setText("Humidity: 36%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[4]))
        {
            myCity.setText("PESHAWAR");
            temperature.setText("10 °C");
            weather.setText("Overcast");
            humidity.setText("Humidity: 93%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[5]))
        {
            myCity.setText("MURREE");
            temperature.setText("8 °C");
            weather.setText("Overcast");
            humidity.setText("Humidity: 93%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[6]))
        {
            myCity.setText("LONDON");
            temperature.setText("9 °C");
            weather.setText("Mostly Cloudy");
            humidity.setText("Humidity: 90%");
            rain.setText("");
        }
        
        else if(city.equals(info[7]))
        {
            myCity.setText("PARIS");
            temperature.setText("11 °C");
            weather.setText("ostly Cloudy");
            humidity.setText("Humidity: 79%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[8]))
        {
            myCity.setText("NEW YORK");
            temperature.setText("2 °C");
            weather.setText("Sunny");
            humidity.setText("Humidity: 54%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[9]))
        {
            myCity.setText("NEW DEHLI");
            temperature.setText("22 °C");
            weather.setText("Smoke");
            humidity.setText("Humidity: 58%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[10]))
        {
            myCity.setText("MUMBAI");
            temperature.setText("29 °C");
            weather.setText("Haze");
            humidity.setText("Humidity: 93%");
            rain.setText("Rain Unlikely");
        }
              
        else if(city.equals(info[11]))
        {
            myCity.setText("HYDERABAD");
            temperature.setText("23 °C");
            weather.setText("Clear with periodic clouds");
            humidity.setText("Humidity: 49%");
            rain.setText("Rain Unlikely");
        }
        
        else if(city.equals(info[12]))
        {
            myCity.setText("RAWALPINDI");
            temperature.setText("16 °C");
            weather.setText("Clear");
            humidity.setText("Humidity: 76%");
            rain.setText("Rain Unlikely");
        }
        
        else
                {
                    textField.setText("CITY NOT FOUND");
                    myCity.setText("");
                    temperature.setText("");
                    weather.setText("");
                    humidity.setText("");
                    rain.setText("");
                }
    
    }
    
    public void processWindowEvent(WindowEvent e) 
    {
        if (e.getID() == WindowEvent.WINDOW_CLOSING) 
        {
            this.setVisible(false);
            new Apps().setVisible(true);
        
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(WeatherApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(WeatherApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(WeatherApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(WeatherApplication.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new WeatherApplication().setVisible(true);
            }
        });
        
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton checkWeather;
    private javax.swing.JLabel humidity;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel myCity;
    private javax.swing.JLabel rain;
    private javax.swing.JLabel temperature;
    private javax.swing.JTextField textField;
    private javax.swing.JLabel weather;
    // End of variables declaration//GEN-END:variables
}
